### ISSUE TITLE
Lore Module Review

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaDAO/realms-react#181]
Some of these could probably be implemented post-Alpha:

- [ ] Further contextual menus for POIs on entity creation (e.g secondary popup that show a list of resources or orders after initial POI type selected)
- [ ] Wonders are currently unlinked (display as unlinked wonder [34] with no link to Realm)
- [ ] Should all POIs link to a frontend component (e.g Resources do not link anywhere and don't currently have a logical frontend component @ponderingdemocritus). We could manage content through Lore Entity submissions - but probably a little tedious)
- [x] Filtering/search system for All Scrolls tab to find scrolls with certain Author/Title/Excerpt?
- [ ] Filtering with POIs
- [ ] A few more POIs added across the components/contracts (Lord/Wallet, Loot Bags, Loot Items, GAs, Atlas co-ordinates, Raid ID) 

@micksabox My feedback, also could be implemented post-alpha:
- [ ] Within the list, display preview of selected story in right sidebar
- [x] Within the create story, display preview of rendered markdown in right sidebar
- [ ] Show a link to page with supported markdown syntax (could be third-party)
- [x] Display share URL and allow copying to clipboard in addition to Twitter share

New ideas:
- [ ] Add toast after successfully adding to StarkNet
- [ ] Show to Player that it's being indexed

**Comment by micksabox** [comment]
My feedback, also could be implemented post-alpha:
- Within the list, display preview of selected story in right sidebar
- Within the create story, display preview of rendered markdown in right sidebar
- Show a link to page with supported markdown syntax (could be third-party)
- Display share URL and allow copying to clipboard in addition to Twitter share

**Comment by ponderingdemocritus** [comment]
@lordabrax - have these been implemented?

**Comment by lordabrax** [comment]
@ponderingdemocritus Partially, yes. POI logic needs a bit more polishing (for "Wonders are currently unlinked", and "Should all POIs link to a frontend component").
